In [52]:
import numpy as np
new2dArray=np.array([[1,2,3],[4,5,3],[23,23,2]])
print("-------the Original array\n",new2dArray)
print("-------slice the first row\n",new2dArray[0])
print("-------different ways to grab element in 2d arr\n [0],[2]=>",new2dArray[0][2],"\n[0,2]=>",new2dArray[0,2])

print("-------slice of 2d array\n", new2dArray[:2,1:])
print("-------Larger subsection\n", new2dArray[:2])


-------the Original array
 [[ 1  2  3]
 [ 4  5  3]
 [23 23  2]]
-------slice the first row
 [1 2 3]
-------different ways to grab element in 2d arr
 [0],[2]=> 3 
[0,2]=> 3
-------slice of 2d array
 [[2 3]
 [5 3]]
-------Larger subsection
 [[1 2 3]
 [4 5 3]]
-------array
 [ 1  2  3  4  5  6  7  8  9 10] 
get all greater than 5 returns a boolean array
 [False False False False False  True  True  True  True  True] 
-------see down
[False False False False False  True  True  True  True  True]
-------to get values we have to pass them

[ 6  7  8  9 10]


In [ ]:

#conditional selection
arr=np.arange(1,11)
print("-------array\n",arr,"\nget all greater than 5 returns a boolean array\n",arr>5,"\n-------see down")
boolArr=arr>5
print(boolArr)

print("-------to get values we have to pass them\n")
print(arr[boolArr])



In [64]:

#exercise to get a section of array 
#method > first get the rows then aim for column
arr=np.arange(1,51).reshape(5,10)
print(arr)
#get the rows which has 13,14 and 23,24>
print("rows with 13,14 and 23,24\n",arr[1:3])

print("target the columns now,2nd to 4th column\n")
print("Select a portion\n",arr[1:3,2:4])

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]
rows with 13,14 and 23,24
 [[11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
target the columns now,2nd to 4th column

Select a portion
 [[13 14]
 [23 24]]


Numpy Operations

In [ ]:

import numpy as np
arr=np.arange(1,11)
print("arithmatic operation",arr+arr)
print("recall",np.ones(4))
print("scalar operation>>>power",arr**2)
print("scalar operation>>>power",arr*100)
print("exponential>>\n",np.exp(arr))
print("SINE>>\n",np.sin(arr))
print("Log>>\n",np.log(arr))
